default:
  - yolov6n
  - scdepthv3
  - ssd_mobilenet_v1
  - repvgg_a0_person_reid_512
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/video/example.mp4
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/video/example_640.mp4
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/video/face_recognition.mp4
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/video/tiling_visdrone_720p.mp4
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/configs/scrfd.json
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/configs/barcode_labels.json
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/configs/yolov5m_seg.json
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/configs/yolov5n_seg.json
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/configs/visdrone.json
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/configs/hailo_4_classes.json

hailo10:
  - "https://dev-public.hailo.ai/v5.1.1/blob/Qwen2-VL-2B-Instruct.hef"
  - "https://dev-public.hailo.ai/v5.1.1/blob/Qwen2.5-1.5B-Instruct.hef"
  - "https://dev-public.hailo.ai/v5.1.1/blob/Whisper-Base.hef"
  - "https://dev-public.hailo.ai/v5.1.1/blob/Qwen2.5-Coder-1.5B-Instruct.hef"
  - yolov8m
  - yolov5m_seg
  - yolov8m_pose
  - scrfd_10g
  - arcface_mobilefacenet
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h15/ocr_det.hef
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h15/ocr.hef
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/hailo10h/hailo_yolov8n_4_classes_vga.hef

hailo8:
  - yolov8m
  - yolov5m_seg
  - yolov8m_pose
  - scrfd_10g
  - arcface_mobilefacenet
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h8/ocr_det.hef
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h8/ocr.hef
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h8/ssd_mobilenet_v1_visdrone.hef
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h8/hailo_yolov8n_4_classes_vga.hef

hailo8l:
  - yolov8s
  - yolov5n_seg
  - yolov8s_pose
  - scrfd_2.5g
  - arcface_mobilefacenet
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h8l_rpi/ssd_mobilenet_v1_visdrone.hef
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h8l/hailo_yolov8n_4_classes_vga.hef

all:
  - yolov8s_pose
  - yolov8s
  - yolov8m_pose
  - yolov8m
  - yolov6n
  - yolov5n_seg
  - yolov5m_wo_spp
  - yolov5m_seg
  - yolov11s
  - yolov11n
  - scdepthv3

retrain:
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/hefs/h8l_rpi/yolov8s-hailo8l-barcode.hef
  - https://hailo-csdata.s3.eu-west-2.amazonaws.com/resources/video/barcode.mp4



